# See config.example.yml for documentation.
object: orig/SSQE01/sys/main.dol
hash: afe7ff0100ddd758ffa7980f18de3eacd8a04659
symbols: config/SSQE01/symbols.txt
splits: config/SSQE01/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11

modules: